services:
  - type: web
    name: dhirstra-backend
    runtime: node
    rootDir: src/backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: MYSQL_PORT
        sync: false
      - key: CORS_ORIGIN
        sync: false
